Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using V3.Data;
using V3.Models;

namespace V3.Controllers
{
    public class MovieController : Controller
    {
    
        private ApplicationDbContext _context;

        public MovieController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


        public ActionResult Random()
        {
            var Movies = _context.Movies.ToList();
            return View(Movies);
        }

       public ActionResult Details(int id)
        {
            var movies = _context.Movies.SingleOrDefault(m => m.ID == id);
      
            if (movies == null)
            {
                return NotFound();
            }

            return View(movies);
        }

       


        public ActionResult Index(int? Pageindex, String Sortby)
        {
            if (!Pageindex.HasValue)
                Pageindex = 1;

            if (string.IsNullOrWhiteSpace(Sortby))
                Sortby = "name";

            return Content (string.Format($"Pageindex={Pageindex}&Sortby = {Sortby}"));
        }


        //[Route("movies/Advanced/{year}/{month}")]
        public ActionResult Advanced(int year, int month)
        {
            return Content(year + "/" + month);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - V3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-Lumen.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/V3.styles.css" asp-append-version="true" />


    <link href="~/lib/DataTables/css/jquery.dataTables.css" rel="stylesheet" />
    <link href="~/lib/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">V3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Random">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Form">Sign Up</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - V3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/DataTables/js/jquery.dataTables.js"></script>
    <script src="~/lib/DataTables/js/dataTables.bootstrap4.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  

    <script src="~/js/site.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>